-- Update galleries table to add cover_image column
ALTER TABLE galleries
ADD COLUMN cover_image VARCHAR(255) NULL AFTER description,
MODIFY COLUMN name VARCHAR(255) NOT NULL,
MODIFY COLUMN description TEXT NULL,
ADD COLUMN created_by INT NULL AFTER cover_image,
ADD COLUMN is_active BOOLEAN DEFAULT TRUE AFTER created_by,
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD FOREIGN KEY (created_by) REFERENCES users(id);
